{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netdisco.fullname" . }}-scheduler
  labels:
    {{- include "netdisco.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: {{ .Values.scheduler.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "netdisco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        {{- include "netdisco.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "netdisco.vaultAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "netdisco.serviceAccountName" . }}
      securityContext:
        {{- include "netdisco.securityContext" . | nindent 8 }}
      {{- if include "netdisco.credentialsEnabled" . }}
      initContainers:
        {{- include "netdisco.initContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-backend"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "netdisco.env" . | nindent 12 }}
            - name: NETDISCO_WORKERS_TASKS
              value: "0"
            {{- with .Values.scheduler.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- include "netdisco.volumeMounts" . | nindent 12 }}
          {{- with .Values.scheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "netdisco.volumes" . | nindent 8 }}
{{- end }}
